# Generated by Django 5.1.7 on 2025-03-21 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название парковки')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Платная парковка')),
                ('price_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена за час (BYN)')),
            ],
            options={
                'verbose_name': 'Парковка',
                'verbose_name_plural': 'Парковки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название помещения')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Площадь (м²)')),
                ('capacity', models.PositiveIntegerField(verbose_name='Количество мест')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена (BYN)')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала бронирования')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания бронирования')),
            ],
            options={
                'verbose_name': 'Помещение',
                'verbose_name_plural': 'Помещения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название оборудования')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='booking.space', verbose_name='Пространство')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('user_contact', models.CharField(max_length=255, verbose_name='Контакт пользователя')),
                ('date', models.DateTimeField(verbose_name='Дата бронирования')),
                ('duration', models.PositiveIntegerField(verbose_name='Продолжительность (часов)')),
                ('confirmed', models.BooleanField(default=True, verbose_name='Подтверждено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.space', verbose_name='Помещение')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-created_at'],
            },
        ),
    ]
