# Generated by Django 5.1.7 on 2025-03-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания бронирования'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateTimeField(verbose_name='Дата начала бронирования'),
        ),
    ]
