# Generated by Django 5.1.7 on 2025-03-26 22:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['event_start_date'], 'verbose_name': 'Бронирование', 'verbose_name_plural': 'Бронирования'},
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='event_date',
            new_name='event_end_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='event_start_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
