# Generated by Django 5.1.7 on 2025-03-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='available',
        ),
        migrations.AddField(
            model_name='space',
            name='area',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='space',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
    ]
