# Generated by Django 5.1.7 on 2025-03-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_end_date_alter_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Продолжительность (часов)'),
        ),
    ]
