# Generated by Django 5.1.7 on 2025-03-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_space_available_space_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='area',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='space',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
