# Generated by Django 5.1.7 on 2025-03-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='space',
            name='start_date',
        ),
        migrations.AddField(
            model_name='space',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание зала'),
        ),
        migrations.AddField(
            model_name='space',
            name='floor',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='space',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название зала'),
        ),
        migrations.AlterField(
            model_name='space',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за час (BYN)'),
        ),
    ]
