# Generated by Django 5.1.7 on 2025-03-29 20:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_space_area_alter_space_price_per_hour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='test_name', help_text='Название', max_length=20, verbose_name='Название')),
                ('description', models.TextField(default='test_description', help_text='Описание', verbose_name='Описание')),
                ('all_count', models.PositiveIntegerField(default=1, help_text='Количество', verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Дополнительная опция',
                'verbose_name_plural': 'Дополнительные опции',
            },
        ),
        migrations.AlterModelOptions(
            name='space',
            options={'verbose_name': 'Пространство', 'verbose_name_plural': 'Пространства'},
        ),
        migrations.RemoveField(
            model_name='space',
            name='price_per_hour',
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[(1, 'Свободно'), (2, 'Забронировано')], default=1, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='space',
            name='description',
            field=models.TextField(default='test_description', help_text='Описание', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='contact_method',
            field=models.CharField(max_length=50, verbose_name='Контактные данные'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='event_end_date',
            field=models.DateTimeField(verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='event_format',
            field=models.CharField(max_length=100, verbose_name='Формат мероприятия'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='event_start_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guests_count',
            field=models.PositiveIntegerField(verbose_name='Количество гостей'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='preferences',
            field=models.JSONField(verbose_name='Предпочтения'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='promo_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.space', verbose_name='Пространство'),
        ),
        migrations.AlterField(
            model_name='space',
            name='area',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='space',
            name='capacity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='space',
            name='name',
            field=models.CharField(default='test_name', help_text='Название', max_length=20, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='PriceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_new_price', models.DateField(default=datetime.datetime.now)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('option_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_of_option', to='booking.option')),
            ],
            options={
                'verbose_name': 'Цены на дополнительные услуги',
            },
        ),
        migrations.CreateModel(
            name='PriceSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_new_price', models.DateField(default=datetime.datetime.now)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('space_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_of_space', to='booking.space')),
            ],
            options={
                'verbose_name': 'Цены на помещения',
            },
        ),
    ]
