# Generated by Django 5.1.7 on 2025-03-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_booking_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='preferences',
            field=models.JSONField(default=dict, verbose_name='Предпочтения'),
        ),
    ]
