# Generated by Django 5.1.7 on 2025-03-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_booking_preferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Предпочтения')),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='preferences',
        ),
        migrations.AddField(
            model_name='booking',
            name='preferences',
            field=models.ManyToManyField(to='booking.preference', verbose_name='Предпочтения'),
        ),
    ]
