# Generated by Django 5.1.7 on 2025-03-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_preference_remove_booking_preferences_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Предпочтение'),
        ),
    ]
