# Generated by Django 5.1.7 on 2025-03-31 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_preference_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Дополнительные предпочтение')),
            ],
        ),
        migrations.DeleteModel(
            name='Preference',
        ),
        migrations.AlterField(
            model_name='booking',
            name='preferences',
            field=models.ManyToManyField(to='booking.additionalpreference', verbose_name='Дополнительные предпочтения'),
        ),
    ]
