# Generated by Django 5.1.7 on 2025-03-31 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_additionalpreference_delete_preference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='space',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.space', verbose_name='Пространство'),
        ),
    ]
