# Generated by Django 5.1.7 on 2025-03-31 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_alter_booking_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalpreference',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Дополнительные предпочтения'),
        ),
        migrations.AlterField(
            model_name='option',
            name='description',
            field=models.TextField(default='Не указано', help_text='Описание', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='option',
            name='name',
            field=models.CharField(default='Не указано', help_text='Название', max_length=20, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='space',
            name='area',
            field=models.PositiveIntegerField(default=1, help_text='Площадь', verbose_name='Площадь'),
        ),
        migrations.AlterField(
            model_name='space',
            name='capacity',
            field=models.PositiveIntegerField(default=1, help_text='Количество мест', verbose_name='Количество мест'),
        ),
        migrations.AlterField(
            model_name='space',
            name='description',
            field=models.TextField(default='Не указано', help_text='Описание', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='space',
            name='name',
            field=models.CharField(default='Не указано', help_text='Название', max_length=20, verbose_name='Название'),
        ),
    ]
