# Generated by Django 5.1.7 on 2025-03-31 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_alter_additionalpreference_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='preferences',
            field=models.ManyToManyField(blank=True, null=True, to='booking.additionalpreference', verbose_name='Дополнительные предпочтения'),
        ),
    ]
