# Generated by Django 5.1.7 on 2025-04-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_alter_booking_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalpreference',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Дополнительные опции'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='preferences',
            field=models.ManyToManyField(blank=True, to='booking.additionalpreference', verbose_name='Дополнительные опции'),
        ),
    ]
