# Generated by Django 5.1.7 on 2025-04-01 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_alter_additionalpreference_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalpreference',
            options={'verbose_name': 'Дополнительные опции', 'verbose_name_plural': 'Дополнительные опции'},
        ),
    ]
