# Generated by Django 5.1.7 on 2025-04-01 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_alter_additionalpreference_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priceoption',
            name='option_id',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='PriceOption',
        ),
    ]
