# Generated by Django 5.1.7 on 2025-04-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0021_alter_booking_event_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='email',
        ),
        migrations.AddField(
            model_name='feedback',
            name='call_time',
            field=models.TimeField(default='12:00', verbose_name='Время звонка'),
        ),
    ]
